export const NAVY_RANKS = [
  { code: "E1", name: "Seaman Recruit" },
  { code: "E2", name: "Seaman Apprentice" },
  { code: "E3", name: "Seaman" },
  { code: "E4", name: "Petty Officer Third Class" },
  { code: "E5", name: "Petty Officer Second Class" },
  { code: "E6", name: "Petty Officer First Class" },
  { code: "E7", name: "Chief Petty Officer" },
  { code: "E8", name: "Senior Chief Petty Officer" },
  { code: "E9", name: "Master Chief Petty Officer" }
] as const;

export const NAVY_RATES = [
  "AB", "ABE", "ABF", "ABH", "AC", "AD", "AE", "AG", "AM", "AME", "AO", "AS", "AT", "ATI", "ATO",
  "AW", "AWF", "AWO", "AWR", "AWS", "AWV", "AZ", "BM", "BU", "CE", "CM", "CS", "CSS", "CT", "CTI",
  "CTM", "CTR", "CTT", "CWT", "DC", "EA", "EM", "EMN", "EN", "EO", "EOD", "ET", "ETN",
  "ETV", "FC", "FCA", "FT", "GM", "GSE", "GSM", "HM", "HT", "IC", "IS", "IT", "ITE",
  "ITN", "ITR", "LN", "LS", "LSS", "MA", "MC", "MM", "MMA", "MMN", "MN", "MR", "MT",
  "MU", "ND", "OS", "PR", "PS", "QM", "RP", "RS", "RW", "SB", "SO", "ST", "STG", "STS",
  "SW", "TM", "UT", "YN", "YNS"
] as const;

export const NAVY_RATINGS = [
  { code: "AB", name: "Aviation Boatswain's Mate" },
  { code: "ABE", name: "Aviation Boatswain's Mate - Equipment" },
  { code: "ABF", name: "Aviation Boatswain's Mate - Fuels" },
  { code: "ABH", name: "Aviation Boatswain's Mate - Handling" },
  { code: "AC", name: "Air Traffic Controller" },
  { code: "AD", name: "Aviation Machinist's Mate" },
  { code: "AE", name: "Aviation Electrician's Mate" },
  { code: "AG", name: "Aerographer's Mate" },
  { code: "AM", name: "Aviation Structural Mechanic" },
  { code: "AME", name: "Aviation Structural Mechanic - Equipment" },
  { code: "AO", name: "Aviation Ordnanceman" },
  { code: "AS", name: "Aviation Support Equipment Technician" },
  { code: "AT", name: "Aviation Electronics Technician" },
  { code: "ATI", name: "Aviation Electronics Technician - Intermediate" },
  { code: "ATO", name: "Aviation Electronics Technician - Organizational" },
  { code: "AW", name: "Naval Aircrewman" },
  { code: "AWF", name: "Naval Aircrewman - Mechanical" },
  { code: "AWO", name: "Naval Aircrewman - Operator" },
  { code: "AWR", name: "Naval Aircrewman - Helicopter" },
  { code: "AWS", name: "Naval Aircrewman - Helicopter" },
  { code: "AWV", name: "Naval Aircrewman - Avionics" },
  { code: "AZ", name: "Aviation Maintenance Administrationman" },
  { code: "BM", name: "Boatswain's Mate" },
  { code: "BU", name: "Builder" },
  { code: "CE", name: "Construction Electrician" },
  { code: "CM", name: "Construction Mechanic" },
  { code: "CS", name: "Culinary Specialist" },
  { code: "CSS", name: "Culinary Specialist - Submarine" },
  { code: "CT", name: "Cryptologic Technician" },
  { code: "CTI", name: "Cryptologic Technician - Interpretive" },
  { code: "CTM", name: "Cryptologic Technician - Maintenance" },
  { code: "CTR", name: "Cryptologic Technician - Collection" },
  { code: "CTT", name: "Cryptologic Technician - Technical" },
  { code: "CWT", name: "Cryptologic Warfare Technician" },
  { code: "DC", name: "Damage Controlman" },
  { code: "EA", name: "Engineering Aide" },
  { code: "EM", name: "Electrician's Mate" },
  { code: "EMN", name: "Electrician's Mate - Nuclear" },
  { code: "EN", name: "Engineman" },
  { code: "EO", name: "Equipment Operator" },
  { code: "EOD", name: "Explosive Ordnance Disposal Technician" },
  { code: "ET", name: "Electronics Technician" },
  { code: "ETN", name: "Electronics Technician - Nuclear" },
  { code: "ETV", name: "Electronics Technician - Submarine Navigation" },
  { code: "FC", name: "Fire Controlman" },
  { code: "FCA", name: "Fire Controlman - Aegis" },
  { code: "FT", name: "Fire Control Technician" },
  { code: "GM", name: "Gunner's Mate" },
  { code: "GSE", name: "Gas Turbine Systems Technician - Electrical" },
  { code: "GSM", name: "Gas Turbine Systems Technician - Mechanical" },
  { code: "HM", name: "Hospital Corpsman" },
  { code: "HT", name: "Hull Maintenance Technician" },
  { code: "IC", name: "Interior Communications Electrician" },
  { code: "IS", name: "Intelligence Specialist" },
  { code: "IT", name: "Information Systems Technician" },
  { code: "ITE", name: "Information Systems Technician - Enlisted" },
  { code: "ITN", name: "Information Systems Technician - Submarine" },
  { code: "ITR", name: "Information Systems Technician - Radio" },
  { code: "LN", name: "Legalman" },
  { code: "LS", name: "Logistics Specialist" },
  { code: "LSS", name: "Logistics Specialist - Submarine" },
  { code: "MA", name: "Master-at-Arms" },
  { code: "MC", name: "Mass Communication Specialist" },
  { code: "MM", name: "Machinist's Mate" },
  { code: "MMA", name: "Machinist's Mate - Aviation" },
  { code: "MMN", name: "Machinist's Mate - Nuclear" },
  { code: "MN", name: "Mineman" },
  { code: "MR", name: "Machinery Repairman" },
  { code: "MT", name: "Missile Technician" },
  { code: "MU", name: "Musician" },
  { code: "ND", name: "Navy Diver" },
  { code: "OS", name: "Operations Specialist" },
  { code: "PR", name: "Aircrew Survival Equipmentman" },
  { code: "PS", name: "Personnel Specialist" },
  { code: "QM", name: "Quartermaster" },
  { code: "RP", name: "Religious Program Specialist" },
  { code: "RS", name: "Retail Services Specialist" },
  { code: "RW", name: "Retail Specialist" },
  { code: "SB", name: "Special Warfare Boat Operator" },
  { code: "SO", name: "Special Warfare Operator" },
  { code: "ST", name: "Sonar Technician" },
  { code: "STG", name: "Sonar Technician - Surface" },
  { code: "STS", name: "Sonar Technician - Submarine" },
  { code: "SW", name: "Steelworker" },
  { code: "TM", name: "Torpedoman's Mate" },
  { code: "UT", name: "Utilitiesman" },
  { code: "YN", name: "Yeoman" },
  { code: "YNS", name: "Yeoman - Submarine" }
] as const;

export type NavyRank = typeof NAVY_RANKS[number]["code"];
export type NavyRating = typeof NAVY_RATINGS[number]["code"];
export type NavyRate = typeof NAVY_RATES[number];